"""create users table with uuid

Revision ID: 763132fc791b
Revises: 
Create Date: 2026-08-22 17:52:46.446478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '763132fc791b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_super_user', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='user_schema'
    )
    op.create_index(op.f('ix_user_schema_users_username'), 'users', ['username'], unique=True, schema='user_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_schema_users_username'), table_name='users', schema='user_schema')
    op.drop_table('users', schema='user_schema')
    # ### end Alembic commands ###
